services:
  frontend:
    image: example-frontend
    container_name: example-frontend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost/api
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    image: example-backend
    container_name: example-backend
    environment:
      - REQUEST_ORIGIN=http://localhost
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DATABASE=postgres_db
    depends_on:
      - redis
      - postgres

  redis:
    image: redis
    container_name: redis

  postgres:
    image: postgres
    container_name: db_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres_db
    volumes:
      - ./database:/var/lib/postgresql/data

  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
