# Start from the provided base image
FROM devopsdockeruh/simple-web-service:alpine

# Provide the default argument to the existing ENTRYPOINT
CMD ["server"]

# Run commands:
# docker build -t web-server .
# docker run web-server